import '../../contracts/contrato_tb_esquema.dart';
import 'colunas_entidade.dart';
import 'tb_categoria.dart';

class TbItemRecorrente implements ContratoTbEsquema {
  static const String nomeTabela = 'tb_item_recorrente';

  static const String colunaId = 'id_item_recorrente';
  static const String colunaIdCategoria = 'id_categoria';
  static const String colunaTitulo = ColunasEntidade.titulo;
  static const String colunaTipoMedida = 'tipo_medida';
  static const String colunaDataCriacao = ColunasEntidade.dataCriacao;
  static const String colunaDataAlteracao = ColunasEntidade.dataAlteracao;
  static const String colunaExcluido = ColunasEntidade.excluido;

  static const String criarTabela = '''
    CREATE TABLE $nomeTabela (
      $colunaId INTEGER PRIMARY KEY AUTOINCREMENT,
      $colunaIdCategoria INTEGER NOT NULL,
      $colunaTitulo TEXT NOT NULL,
      $colunaTipoMedida TEXT NOT NULL,
      $colunaDataCriacao TIMESTAMP NOT NULL DEFAULT ${ColunasEntidade.dataAtualUtc},
      $colunaDataAlteracao TIMESTAMP NOT NULL DEFAULT ${ColunasEntidade.dataAtualUtc},
      $colunaExcluido INTEGER NOT NULL DEFAULT 0,
      FOREIGN KEY ($colunaIdCategoria) REFERENCES ${TbCategoria.nomeTabela}(${TbCategoria.colunaId}) ON UPDATE CASCADE ON DELETE CASCADE
    )
  ''';

  static const String recuperarTodos =
      ''' SELECT * FROM $nomeTabela WHERE $colunaExcluido = 0 ORDER BY $colunaTitulo ASC''';

  static const String inserirItensRecorrentes =
      '''INSERT INTO $nomeTabela ($colunaIdCategoria, $colunaTitulo, $colunaTipoMedida) VALUES
            -- Higiene Pessoal (1)
            (1,'Sabonete','und'),
            (1,'Shampoo','und'),
            (1,'Condicionador','und'),
            (1,'Creme Dental','und'),
            (1,'Escova de Dente','und'),
            (1,'Fio Dental','und'),
            (1,'Enxaguante Bucal','und'),
            (1,'Desodorante','und'),
            (1,'Papel Higiênico','und'),
            (1,'Algodão','und'),
            (1,'Cotonete','und'),
            (1,'Absorvente','und'),
            (1,'Barbeador','und'),
            (1,'Creme de Barbear','und'),
            (1,'Lenço Umedecido','und'),
            (1,'Protetor Solar','und'),
            (1,'Hidratante Corporal','und'),
            (1,'Sabonete Íntimo','und'),
            (1,'Álcool Gel','und'),
            (1,'Esponja de Banho','und'),

            -- Limpeza (2) - 35 itens
            (2,'Detergente','und'),
            (2,'Sabão em Pó','und'),
            (2,'Sabão Líquido','und'),
            (2,'Amaciante','und'),
            (2,'Água Sanitária','und'),
            (2,'Desinfetante','und'),
            (2,'Limpador Multiuso','und'),
            (2,'Lustra Móveis','und'),
            (2,'Limpa Vidros','und'),
            (2,'Esponja','und'),
            (2,'Palha de Aço','und'),
            (2,'Saco de Lixo','und'),
            (2,'Pano de Chão','und'),
            (2,'Pano de Microfibra','und'),
            (2,'Vassoura','und'),
            (2,'Rodo','und'),
            (2,'Balde','und'),
            (2,'Luva de Limpeza','und'),
            (2,'Inseticida','und'),
            (2,'Odorizador de Ambiente','und'),
            (2,'Limpa Alumínio','und'),
            (2,'Limpa Forno','und'),
            (2,'Limpa Piso','und'),
            (2,'Limpa Banheiro','und'),
            (2,'Tira Limo','und'),
            (2,'Cloro Gel','und'),
            (2,'Desengordurante','und'),
            (2,'Refil Mop','und'),
            (2,'Esponja Mágica','und'),
            (2,'Flanela','und'),
            (2,'Escova de Limpeza','und'),
            (2,'Limpa Inox','und'),
            (2,'Pastilha Sanitária','und'),
            (2,'Limpa Carpete','und'),
            (2,'Sabão em Barra','und'),

            -- Mercearia (3) - 40 itens
            (3,'Arroz','kg'),
            (3,'Feijão Carioca','kg'),
            (3,'Feijão Preto','kg'),
            (3,'Macarrão','und'),
            (3,'Açúcar','kg'),
            (3,'Sal','kg'),
            (3,'Farinha de Trigo','kg'),
            (3,'Farinha de Mandioca','kg'),
            (3,'Fubá','kg'),
            (3,'Café','kg'),
            (3,'Óleo de Soja','und'),
            (3,'Azeite','und'),
            (3,'Molho de Tomate','und'),
            (3,'Extrato de Tomate','und'),
            (3,'Milho Verde','und'),
            (3,'Ervilha','und'),
            (3,'Atum','und'),
            (3,'Sardinha','und'),
            (3,'Maionese','und'),
            (3,'Ketchup','und'),
            (3,'Mostarda','und'),
            (3,'Vinagre','und'),
            (3,'Achocolatado','und'),
            (3,'Leite de Coco','und'),
            (3,'Creme de Leite','und'),
            (3,'Leite Condensado','und'),
            (3,'Aveia','kg'),
            (3,'Granola','kg'),
            (3,'Lentilha','kg'),
            (3,'Grão-de-Bico','kg'),
            (3,'Canjica','kg'),
            (3,'Pipoca','kg'),
            (3,'Gelatina','und'),
            (3,'Fermento Químico','und'),
            (3,'Fermento Biológico','und'),
            (3,'Biscoito Água e Sal','und'),
            (3,'Biscoito Recheado','und'),
            (3,'Macarrão Instantâneo','und'),
            (3,'Arroz Integral','kg'),
            (3,'Feijão Fradinho','kg'),

            -- Hortifruti (4) - 35 itens
            (4,'Banana','kg'),
            (4,'Maçã','kg'),
            (4,'Laranja','kg'),
            (4,'Limão','kg'),
            (4,'Mamão','kg'),
            (4,'Melancia','kg'),
            (4,'Melão','kg'),
            (4,'Abacaxi','und'),
            (4,'Manga','kg'),
            (4,'Uva','kg'),
            (4,'Morango','kg'),
            (4,'Pera','kg'),
            (4,'Tomate','kg'),
            (4,'Batata','kg'),
            (4,'Batata Doce','kg'),
            (4,'Cebola','kg'),
            (4,'Alho','kg'),
            (4,'Cenoura','kg'),
            (4,'Beterraba','kg'),
            (4,'Abobrinha','kg'),
            (4,'Pepino','kg'),
            (4,'Chuchu','kg'),
            (4,'Berinjela','kg'),
            (4,'Pimentão','kg'),
            (4,'Alface','und'),
            (4,'Couve','und'),
            (4,'Repolho','kg'),
            (4,'Espinafre','und'),
            (4,'Brócolis','und'),
            (4,'Couve-flor','und'),
            (4,'Mandioca','kg'),
            (4,'Inhame','kg'),
            (4,'Quiabo','kg'),
            (4,'Rúcula','und'),
            (4,'Cheiro Verde','und'),

            -- Frios (5)
            (5,'Presunto','kg'),
            (5,'Mussarela','kg'),
            (5,'Peito de Peru','kg'),
            (5,'Mortadela','kg'),
            (5,'Salame','kg'),
            (5,'Queijo Prato','kg'),
            (5,'Queijo Minas','kg'),
            (5,'Queijo Parmesão','kg'),
            (5,'Queijo Coalho','kg'),
            (5,'Ricota','kg'),
            (5,'Requeijão','und'),
            (5,'Cream Cheese','und'),
            (5,'Margarina','und'),
            (5,'Manteiga','und'),
            (5,'Iogurte','und'),
            (5,'Bebida Láctea','und'),
            (5,'Queijo Brie','kg'),
            (5,'Queijo Gorgonzola','kg'),
            (5,'Provolone','kg'),
            (5,'Lombo Canadense','kg'),

            -- Açougue (6)
            (6,'Carne Moída','kg'),
            (6,'Patinho','kg'),
            (6,'Acém','kg'),
            (6,'Alcatra','kg'),
            (6,'Picanha','kg'),
            (6,'Contra Filé','kg'),
            (6,'Músculo','kg'),
            (6,'Costela Bovina','kg'),
            (6,'Frango Inteiro','kg'),
            (6,'Peito de Frango','kg'),
            (6,'Coxa de Frango','kg'),
            (6,'Sobrecoxa','kg'),
            (6,'Asa de Frango','kg'),
            (6,'Lombo Suíno','kg'),
            (6,'Costela Suína','kg'),
            (6,'Linguiça Toscana','kg'),
            (6,'Bacon','kg'),
            (6,'Cupim','kg'),
            (6,'Filé Mignon','kg'),
            (6,'Pernil','kg'),

            -- Padaria (7)
            (7,'Pão Francês','kg'),
            (7,'Pão de Forma','und'),
            (7,'Pão Integral','und'),
            (7,'Bisnaguinha','und'),
            (7,'Croissant','und'),
            (7,'Sonho','und'),
            (7,'Rosquinha','und'),
            (7,'Bolo Simples','und'),
            (7,'Pão de Queijo','kg'),
            (7,'Torrada','und'),
            (7,'Pão Sírio','und'),
            (7,'Pão Italiano','und'),
            (7,'Baguete','und'),
            (7,'Pão Doce','und'),
            (7,'Cuca','und'),
            (7,'Broa','und'),
            (7,'Pão Australiano','und'),
            (7,'Pão de Hambúrguer','und'),
            (7,'Pão de Hot Dog','und'),
            (7,'Panetone','und'),

            -- Bebidas (8)
            (8,'Água Mineral','und'),
            (8,'Refrigerante Cola','und'),
            (8,'Refrigerante Guaraná','und'),
            (8,'Suco de Laranja','und'),
            (8,'Suco de Uva','und'),
            (8,'Água de Coco','und'),
            (8,'Chá Gelado','und'),
            (8,'Energético','und'),
            (8,'Isotônico','und'),
            (8,'Leite','und'),
            (8,'Café Pronto','und'),
            (8,'Achocolatado Líquido','und'),
            (8,'Água com Gás','und'),
            (8,'Suco Integral','und'),
            (8,'Néctar','und'),
            (8,'Água Saborizada','und'),
            (8,'Bebida Vegetal','und'),
            (8,'Capuccino','und'),
            (8,'Chocolate Quente','und'),
            (8,'Água Tônica','und'),

            -- Confeitaria (9)
            (9,'Chocolate','und'),
            (9,'Bombom','und'),
            (9,'Bala','und'),
            (9,'Pirulito','und'),
            (9,'Paçoca','und'),
            (9,'Pé de Moleque','und'),
            (9,'Doce de Leite','und'),
            (9,'Goiabada','kg'),
            (9,'Marmelada','kg'),
            (9,'Wafer','und'),
            (9,'Cookie','und'),
            (9,'Brownie','und'),
            (9,'Barra de Cereal','und'),
            (9,'Marshmallow','und'),
            (9,'Gelatina','und'),
            (9,'Pudim','und'),
            (9,'Brigadeiro','und'),
            (9,'Beijinho','und'),
            (9,'Biscoito Amanteigado','und'),
            (9,'Trufa','und'),

            -- Bazar (10)
            (10,'Vela','und'),
            (10,'Pilha AA','und'),
            (10,'Pilha AAA','und'),
            (10,'Lâmpada','und'),
            (10,'Copo Descartável','und'),
            (10,'Prato Descartável','und'),
            (10,'Talher Descartável','und'),
            (10,'Filtro de Café','und'),
            (10,'Papel Alumínio','und'),
            (10,'Filme PVC','und'),
            (10,'Palito de Dente','und'),
            (10,'Palito de Churrasco','und'),
            (10,'Isqueiro','und'),
            (10,'Fósforo','und'),
            (10,'Assadeira','und'),
            (10,'Caneca','und'),
            (10,'Copo','und'),
            (10,'Prato','und'),
            (10,'Pote Plástico','und'),
            (10,'Garrafa Térmica','und'),

            -- Pet (11)
            (11,'Ração para Cães','kg'),
            (11,'Ração para Gatos','kg'),
            (11,'Areia Sanitária','kg'),
            (11,'Petisco para Cães','und'),
            (11,'Petisco para Gatos','und'),
            (11,'Shampoo Pet','und'),
            (11,'Condicionador Pet','und'),
            (11,'Tapete Higiênico','und'),
            (11,'Brinquedo Pet','und'),
            (11,'Coleira','und'),
            (11,'Guia','und'),
            (11,'Comedouro','und'),
            (11,'Bebedouro','und'),
            (11,'Antipulgas','und'),
            (11,'Escova Pet','und'),
            (11,'Sachê para Gatos','und'),
            (11,'Osso Mastigável','und'),
            (11,'Granulado','kg'),
            (11,'Roupa Pet','und'),
            (11,'Pá Higiênica','und'),

            -- Congelados (12)
            (12,'Pizza Congelada','und'),
            (12,'Lasanha','und'),
            (12,'Hambúrguer','und'),
            (12,'Batata Frita','kg'),
            (12,'Nuggets','kg'),
            (12,'Legumes Congelados','kg'),
            (12,'Ervilha Congelada','kg'),
            (12,'Milho Congelado','kg'),
            (12,'Açaí','kg'),
            (12,'Sorvete','und'),
            (12,'Polpa de Fruta','kg'),
            (12,'Peixe Empanado','kg'),
            (12,'Frango Empanado','kg'),
            (12,'Pão de Queijo','kg'),
            (12,'Espinafre Congelado','kg'),
            (12,'Brócolis Congelado','kg'),
            (12,'Pizza Broto','und'),
            (12,'Massa Fresca','und'),
            (12,'Waffle','und'),
            (12,'Torta Congelada','und'),

            -- Condimentos (13)
            (13,'Orégano','und'),
            (13,'Manjericão','und'),
            (13,'Alecrim','und'),
            (13,'Salsa Desidratada','und'),
            (13,'Cebolinha Desidratada','und'),
            (13,'Pimenta-do-Reino','und'),
            (13,'Colorau','und'),
            (13,'Páprica','und'),
            (13,'Cominho','und'),
            (13,'Canela','und'),
            (13,'Cravo','und'),
            (13,'Noz-moscada','und'),
            (13,'Açafrão','und'),
            (13,'Tempero Baiano','und'),
            (13,'Caldo de Carne','und'),
            (13,'Caldo de Galinha','und'),
            (13,'Molho Inglês','und'),
            (13,'Shoyu','und'),
            (13,'Molho de Pimenta','und'),
            (13,'Chimichurri','und'),

            -- Laticinios (14)
            (14,'Leite Integral','und'),
            (14,'Leite Desnatado','und'),
            (14,'Leite Semidesnatado','und'),
            (14,'Iogurte Natural','und'),
            (14,'Iogurte Grego','und'),
            (14,'Queijo Mussarela','kg'),
            (14,'Queijo Prato','kg'),
            (14,'Queijo Minas','kg'),
            (14,'Queijo Coalho','kg'),
            (14,'Requeijão','und'),
            (14,'Cream Cheese','und'),
            (14,'Manteiga','und'),
            (14,'Margarina','und'),
            (14,'Leite Condensado','und'),
            (14,'Creme de Leite','und'),
            (14,'Doce de Leite','und'),
            (14,'Ricota','kg'),
            (14,'Parmesão','kg'),
            (14,'Bebida Láctea','und'),
            (14,'Coalhada','und'),

            -- Peixaria (15)
            (15,'Tilápia','kg'),
            (15,'Salmão','kg'),
            (15,'Merluza','kg'),
            (15,'Sardinha','kg'),
            (15,'Atum Fresco','kg'),
            (15,'Camarão','kg'),
            (15,'Lula','kg'),
            (15,'Polvo','kg'),
            (15,'Mexilhão','kg'),
            (15,'Bacalhau','kg'),
            (15,'Pintado','kg'),
            (15,'Pacu','kg'),
            (15,'Corvina','kg'),
            (15,'Filé de Peixe','kg'),
            (15,'Posta de Peixe','kg'),
            (15,'Anchoa','kg'),
            (15,'Ostra','kg'),
            (15,'Caranguejo','kg'),
            (15,'Marisco','kg'),
            (15,'Anchova','kg'),

            -- Cosméticos (16)
            (16,'Tintura','und'),
            (16,'Esmalte','und'),
            (16,'Removedor','und'),
            (16,'Acetona','und'),
            (16,'Algodão','und'),
            (16,'Base para Unhas','und'),
            (16,'Máscara Facial','und'),
            (16,'Creme Facial','und'),
            (16,'Sabonete Facial','und'),
            (16,'Protetor Labial','und'),
            (16,'Perfume','und'),
            (16,'Colônia','und'),
            (16,'Creme para Mãos','und'),
            (16,'Óleo Corporal','und'),
            (16,'Fixador de Cabelo','und'),
            (16,'Gel de Cabelo','und'),
            (16,'Escova de Cabelo','und'),
            (16,'Pente','und'),
            (16,'Lixa de Unha','und'),
            (16,'Cílios Postiços','und'),

            -- Utilidades (17)
            (17,'Prego','und'),
            (17,'Fita de Corte','und'),
            (17,'Fita de Corte','und'),
            (17,'Pilha Botão','und'),
            (17,'Extensão','und'),
            (17,'Fita Isolante','und'),
            (17,'Abraçadeira','und'),
            (17,'Cadeado','und'),
            (17,'Corda','und'),
            (17,'Prego','und'),
            (17,'Parafuso','und'),
            (17,'Bucha','und'),
            (17,'Martelo','und'),
            (17,'Chave de Fenda','und'),
            (17,'Fita Métrica','und'),
            (17,'Supercola','und'),
            (17,'Cola Branca','und'),
            (17,'Tesoura','und'),
            (17,'Estilete','und'),
            (17,'Caixa Organizadora','und'),
            (17,'Cabide','und'),
            (17,'Escorredor','und'),
            (17,'Lixeira','und'),

            -- Sem categoria (18)
            (18,'Carvão','und'),
            (18,'Gelo','kg'),
            (18,'Guardanapo','und'),
            (18,'Vinho sem Álcool','und'),
            (18,'Suplemento Alimentar','und'),
            (18,'Incenso','und'),
            (18,'Velas Decorativas','und'),
            (18,'Sacola Reutilizável','und'),
            (18,'Máscara Descartável','und'),
            (18,'Termômetro','und'),
            (18,'Papel Presente','und'),
            (18,'Fita Adesiva','und'),
            (18,'Envelope','und'),
            (18,'Caderno','und'),
            (18,'Caneta','und'),
            (18,'Lápis','und'),
            (18,'Borracha','und'),
            (18,'Clips','und'),
            (18,'Grampeador','und'),
            (18,'Elástico','und');
  ''';
}
